FusionDev Backup1/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Deliveries__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deliveries</label>
        <referenceTo>Deliveries__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sold_To__c</fullName>
        <formula>Parent.ENSX_EDM__SAP_Customer_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sold To</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

FusionDev Backup1/src/objects/Deliveries__c.object
<CustomObject>
    <description>Deliveries</description>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Deliveries</relationshipLabel>
        <relationshipName>Deliveries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Deliveries (Sold To)</relationshipLabel>
        <relationshipName>Deliveries1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deliveries</label>
    <nameField>
        <label>Pack ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

FusionDev Backup1/src/objects/Delivery_Lines__c.object
<CustomObject>
    <fields>
        <fullName>Deliveries__c</fullName>
        <label>Deliveries</label>
        <referenceTo>Deliveries__c</referenceTo>
        <relationshipLabel>Delivery Lines</relationshipLabel>
        <relationshipName>Delivery_Lines10</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Delivery Lines</label>
    <nameField>
        <label>Delivery Lines Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FusionDev Backup1/src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Sold To)</relationshipLabel>
        <relationshipName>Orders2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

FusionDev Backup1/src/classes/TSTU_DeliverySync_Batch.cls
@isTest
public class TSTU_DeliverySync_Batch
{
    class MockSearch implements ensx.EnosixFramework.SearchSBOMock
    {
        Boolean isSuccess;
        public MockSearch(Boolean isSuccess)
        {
            this.isSuccess = isSuccess;
        }

        public ensx.EnosixFramework.SearchResult executeSearch()
        {
            SBO_YetiDeliverySync_Search.YetiDeliverySync_SR searchResult =
                new SBO_YetiDeliverySync_Search.YetiDeliverySync_SR();

            if (isSuccess)
            {
                SBO_YetiDeliverySync_Search.SEARCHRESULT result = new SBO_YetiDeliverySync_Search.SEARCHRESULT();
                result.CustomerShipment = '1';
                result.DeliveryItemNumber = '10';
                result.ErpOrder = '17';
                result.LastChangeDate = Date.newInstance(2016, 12, 1);
                result.LastChangeTime = Time.newInstance(10, 30, 0, 0);
                result.SoldToParty = '123456768';
                searchResult.SearchResults.add(result);
                SBO_YetiDeliverySync_Search.SEARCHRESULT result2 = new SBO_YetiDeliverySync_Search.SEARCHRESULT();
                result2.CustomerShipment = '2';
                result2.DeliveryItemNumber = '10';
                result2.ErpOrder = '18';
                result2.LastChangeDate = Date.newInstance(2017, 2, 20);
                result2.LastChangeTime = Time.newInstance(13, 50, 0, 0);
                result2.SoldToParty = '12345677';
                searchResult.SearchResults.add(result2);
            }

            searchResult.setSuccess(isSuccess);
            return searchResult;
        }
    }

    @isTest public static void executeTest()
    {
        List<String> allIds = new List<String>();

        ENSX.EnosixFramework.setMock(SBO_YetiDeliverySync_Search.class, new MockSearch(true));
        String notFoundAccountId = UTIL_YetiSyncHelper.getNotFoundAccountId(null);
        System.debug('TSTU_DeliverySync_Batch.executeTest(): NOT_FOUND account Id: ' + notFoundAccountId);
        sObject order = UTIL_SyncHelper.createSObject('Order__c');
        order.put('Sold_To__c', Id.valueOf(notFoundAccountId));
        order.put('Name', '18');
        insert order;

        sObject delivery = UTIL_SyncHelper.createSObject('Deliveries__c');
        delivery.put('Name', '2');
        delivery.put('Sold_To__c', Id.valueOf(notFoundAccountId));
        insert delivery;

        sObject deliveryLine = UTIL_SyncHelper.createSObject('Delivery_Lines__c');
        deliveryLine.put('Name', '2/10');
        deliveryLine.put('Deliveries__c', delivery.get('Id'));
        insert deliveryLine;

        Test.startTest();
        for (Integer i = 0; i < 2; i++)
        {
            UTIL_DeliverySync_Batch deliverSyncBatch = new UTIL_DeliverySync_Batch();
            deliverSyncBatch.setBatchParam(null);
            String schedId = Database.executeBatch(new UTIL_DeliverySync_Batch());
            allIds.add(schedId);
        }
        Test.stopTest();

        //ID in API is of 15 didgits
        for (Integer i =0; i< 2; i++)
        {
            System.assertEquals(15, allIds[i].length());
        }
    }
}