FusionDev Backup1/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Deliveries__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deliveries</label>
        <referenceTo>Deliveries__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inside_Rep_Email__c</fullName>
        <formula>Inside_SR__r.Trading_Post_Email__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Inside Rep Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inside_Rep_Phone__c</fullName>
        <formula>Inside_SR__r.Phone</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Inside Rep Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inside_SR_Name__c</fullName>
        <formula>Inside_SR__r.FirstName + &apos; &apos; + Inside_SR__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Inside Sales Rep</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Outside_Rep_Email__c</fullName>
        <formula>Outside_SR__r.Trading_Post_Email__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>YETI Outside Rep Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Outside_Rep_Phone__c</fullName>
        <formula>Outside_SR__r.Phone</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>YETI Outside Rep Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Outside_SR_Name__c</fullName>
        <formula>Outside_SR__r.FirstName + &apos; &apos; + Outside_SR__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Outside Sales Rep</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO__c</fullName>
        <label>PO</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To__c</fullName>
        <formula>Parent.ENSX_EDM__SAP_Customer_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sold To</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

FusionDev Backup1/src/objects/Deliveries__c.object
<CustomObject>
    <description>Deliveries</description>
    <fields>
        <fullName>Bill_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Deliveries (Bill To)</relationshipLabel>
        <relationshipName>Deliveries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Deliveries</relationshipLabel>
        <relationshipName>Deliveries_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Deliveries</relationshipLabel>
        <relationshipName>Deliveries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_Customer_Number__c</fullName>
        <label>SAP Customer Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_Date__c</fullName>
        <label>Ship Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Deliveries (Ship To)</relationshipLabel>
        <relationshipName>Deliveries2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipping_Method__c</fullName>
        <label>Shipping Method</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Deliveries (Sold To)</relationshipLabel>
        <relationshipName>Deliveries1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tracking_Number__c</fullName>
        <label>Tracking Number</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Deliveries</label>
    <nameField>
        <label>Pack ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

FusionDev Backup1/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Bill_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deliveries__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deliveries</label>
        <referenceTo>Deliveries__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deposit_Balance__c</fullName>
        <label>Deposit Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FOB__c</fullName>
        <label>FOB</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Amount__c</fullName>
        <label>Invoice Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice_Balance__c</fullName>
        <label>Invoice Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Number</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PO__c</fullName>
        <label>PO</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Packing_Slip_ID__c</fullName>
        <formula>Deliveries__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Packing Slip ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Customer_Number__c</fullName>
        <label>SAP Customer Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <label>Sales Order #</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices (Ship To)</relationshipLabel>
        <relationshipName>Invoices2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipping_Amount__c</fullName>
        <label>Shipping Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Shipping_Date__c</fullName>
        <formula>Deliveries__r.Ship_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Shipping Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices (Sold To)</relationshipLabel>
        <relationshipName>Invoices1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Total__c</fullName>
        <label>Sub Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <label>Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Terms__c</fullName>
        <label>Terms</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Before_Discount__c</fullName>
        <label>Total Before Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

FusionDev Backup1/src/objects/Invoice_Lines__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Ext_Price__c</fullName>
        <label>Ext Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PO__c</fullName>
        <label>PO</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <label>Sales Order</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Invoice Lines</label>
    <nameField>
        <label>Invoice Lines Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FusionDev Backup1/src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Bill_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FOB__c</fullName>
        <label>FOB</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Customer_Number__c</fullName>
        <label>SAP Customer Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_Via__c</fullName>
        <label>Ship Via</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_Amount__c</fullName>
        <label>Shipping</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Sold To)</relationshipLabel>
        <relationshipName>Orders2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Total__c</fullName>
        <label>Sub Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <label>Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Terms__c</fullName>
        <label>Terms</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

FusionDev Backup1/src/objects/Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>Order_Line__c</fullName>
        <label>Order Line</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Order Line</label>
    <nameField>
        <label>Order Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FusionDev Backup1/src/classes/Yeti_PrintInvoiceController.cls
/*
Author        :  Rakshit Virmani (Appirio)
Created Date  :  14 March 2017
Name          :  Yeti_PrintInvoiceController
Description   :  Controller for Yeti_printinvoice.page 
Original Task :  T-585056
*/

public with sharing class Yeti_PrintInvoiceController {
  public list<Order_Line__c> lstOrderLineItems{get;set;}
  public list<Invoice__c> lstInvoice{get;set;}
  private Id invoiceId;
  public boolean showDiscount{get;set;}
  public List<String> lstTrackingNumbers{get;set;}
  
  //controls how many quote line items are displayed on page 1
  private static Integer FIRST_BREAK = 7;
  //controls how many quote line items are displayed on subsequent pages
  private static Integer SUBSEQ_BREAKS = 32;
  public List<List<Invoice_Lines__c>> pageBrokenInvoiceLines {get;private set;}

  
  
  //Constructor 
  public Yeti_PrintInvoiceController(){
    lstOrderLineItems = new list<Order_Line__c>();
    lstInvoice = new list<Invoice__c>();
    invoiceId = apexpages.currentpage().getparameters().get('id');
    showDiscount = false;
    pageBrokenInvoiceLines = new List<List<Invoice_Lines__c>>();
    lstTrackingNumbers = new List<String>();
    
    if (invoiceId != null){
      lstInvoice = [SELECT Bill_To__c,Bill_To__r.BillingAddress,Bill_To__r.BillingStreet,Bill_To__r.BillingCity,Bill_To__r.BillingState,Bill_To__r.BillingCountry,
                    Bill_To__r.BillingPostalCode,Ship_To__r.ShippingStreet,Ship_To__r.ShippingCity,Ship_To__r.ShippingState,Ship_To__r.ShippingCountry,Ship_To__r.ShippingPostalCode,
                    Deliveries__r.Tracking_Number__c,Deliveries__r.Name,Deliveries__r.Ship_Date__c,CreatedById,CreatedDate,Deliveries__c,Deposit_Balance__c,Due_Date__c,FOB__c,Id,
                    Invoice_Amount__c,Invoice_Balance__c,Invoice_Date__c,Name,Packing_Slip_ID__c,PO__c,Sales_Order__c,SAP_Customer_Number__c,Deliveries__r.Shipping_Method__c,Order__r.FOB__c,
                    Shipping_Date__c,Ship_To__c,Sold_To__c,Status__c,Terms__c,Order__r.Ship_via__c,Sub_Total__c,Shipping_Amount__c,Tax__c,Total_Before_Discount__c,Discount__c,
                    Sold_To__r.Inside_SR_Name__c,Sold_To__r.Inside_Rep_Phone__c,Sold_To__r.Inside_Rep_Email__c,Sold_To__r.Outside_SR_Name__c,Sold_To__r.Outside_Rep_Phone__c,Sold_To__r.Outside_Rep_Email__c,
                    Sold_To__r.IsPersonAccount,Ship_To__r.IsPersonAccount,Bill_To__r.IsPersonAccount,
                    (SELECT Name,Description__c,Ext_Price__c,Id,Invoice__c,Last_Change_Time__c,Order_Quantity__c,Packing_Line__c,
                    Packing_Slip__c,Part_Number__c,PO__c,Sales_Order__c,Unit_Price__c,Discount__c,UPC__c,Subtotal__c FROM Invoice_Lines__r)
                    FROM Invoice__c 
                    WHERE Id = : invoiceId]; 

        if(String.isNotBlank(lstInvoice[0].Deliveries__r.Tracking_Number__c)) {
          List<String> lstString = new List<String>();
          lstString = lstInvoice[0].Deliveries__r.Tracking_Number__c.split(',');
          Integer counter = 0;
          for (String st : lstString){
            String s = st; 
            if(math.mod(counter,2) != 0){
              s = s + ',' + st;
              lstTrackingNumbers.add(s);
            }
            counter++;
          }
        }

        if(!lstInvoice.isEmpty() && !lstInvoice[0].Invoice_Lines__r.isEmpty()){
          List<Invoice_Lines__c> lstInvoiceLines = new List<Invoice_Lines__c>();
          Integer counter = 0;
          boolean firstBreakFound = false;
          boolean setSubSeqBreak = false;       
          Integer breakPoint = FIRST_BREAK;
          
          for(Invoice_Lines__c invLineItem : lstInvoice[0].Invoice_Lines__r){
            if(invLineItem.Discount__c > 0.00 || invLineItem.Discount__c < 0.00){
              showDiscount = true;
            }
            if(counter <= breakPoint){
              lstInvoiceLines.add(invLineItem);
              counter++;
            }
            if(counter == breakPoint){
              if (!firstBreakFound){
                firstBreakFound = true;
                setSubSeqBreak = true;
              }
              counter = 0;
              pageBrokenInvoiceLines.add(lstInvoiceLines);
              lstInvoiceLines = new List<Invoice_Lines__c>();
            }
            if(setSubSeqBreak){
              breakPoint = SUBSEQ_BREAKS;
              setSubSeqBreak = false;
            }
          }
          if(!lstInvoiceLines.isEmpty())
            pageBrokenInvoiceLines.add(lstInvoiceLines);
        }
    }
  }
}