FusionDev Backup1/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Deliveries__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deliveries</label>
        <referenceTo>Deliveries__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

FusionDev Backup1/src/objects/Deliveries__c.object
<CustomObject>
    <description>Deliveries</description>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Deliveries</relationshipLabel>
        <relationshipName>Deliveries_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Deliveries</relationshipLabel>
        <relationshipName>Deliveries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deliveries</label>
    <nameField>
        <label>Pack ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

FusionDev Backup1/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Deliveries__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deliveries</label>
        <referenceTo>Deliveries__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Number</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

FusionDev Backup1/src/objects/Order__c.object
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

FusionDev Backup1/src/classes/Yeti_printDetailControllerTest.cls
/*
Author        :  Rakshit Virmani (Appirio)
Created Date  :  23rd March 2017
Name          :  Yeti_printDetailControllerTest
Description   :  Test Class for Yeti_printDetailController 
*/
@isTest
public class Yeti_printDetailControllerTest {
  @testSetup
  static void createTestData(){
    YETI_TestDataFactory ytdf = new YETI_TestDataFactory();
    Account acc = ytdf.createAccount('Test Account', true);
    Order__c ord = ytdf.createOrder('Test Order', acc.Id, true);
    Invoice__c inv = ytdf.createInvoice('Test Invoice', acc.Id, true);
    Deliveries__c shipm = ytdf.createDeliveries('Test Shipment', acc.Id, true);
  }
  
  static testmethod void redirectToPdfTest(){
    Test.startTest();
      Order__c ord = [SELECT Id,Name FROM Order__c WHERE Name =: 'Test Order' LIMIT 1];
      ApexPages.currentPage().getParameters().put('id',ord.Id);
      Yeti_printDetailController ypdc = new Yeti_printDetailController();
      ypdc.redirectToPDFPage();
      system.assertEquals(true, ApexPages.currentPage().getParameters().get('id') != null);
    Test.stopTest();
  }
  
  static testmethod void redirectToPdfTestCase2(){
    Test.startTest();
      Invoice__c inv = [SELECT Id,Name FROM Invoice__c WHERE Name =: 'Test Invoice' LIMIT 1];
      ApexPages.currentPage().getParameters().put('id',inv.Id);
      Yeti_printDetailController ypdc = new Yeti_printDetailController();
      ypdc.redirectToPDFPage();
      system.assertEquals(true, ApexPages.currentPage().getParameters().get('id') != null);
    Test.stopTest();
  }
  
  static testmethod void redirectopdfcase3(){
    Test.startTest();
      Deliveries__c del = [SELECT Id,Name FROM Deliveries__c WHERE Name =: 'Test Shipment' LIMIT 1];
      ApexPages.currentPage().getParameters().put('id',del.Id);
      Yeti_printDetailController ypdc = new Yeti_printDetailController();
      ypdc.redirectToPDFPage();
      system.assertEquals(true, ApexPages.currentPage().getParameters().get('id') != null);
    Test.stopTest();
  }
}