FusionDev Backup1/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Deliveries__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deliveries</label>
        <referenceTo>Deliveries__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inside_Rep_Email__c</fullName>
        <formula>Inside_SR__r.Trading_Post_Email__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Inside Rep Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inside_Rep_Phone__c</fullName>
        <formula>Inside_SR__r.Phone</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Inside Rep Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inside_SR_Name__c</fullName>
        <formula>Inside_SR__r.FirstName + &apos; &apos; + Inside_SR__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Inside Sales Rep</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Outside_Rep_Email__c</fullName>
        <formula>Outside_SR__r.Trading_Post_Email__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>YETI Outside Rep Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Outside_Rep_Phone__c</fullName>
        <formula>Outside_SR__r.Phone</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>YETI Outside Rep Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Outside_SR_Name__c</fullName>
        <formula>Outside_SR__r.FirstName + &apos; &apos; + Outside_SR__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Outside Sales Rep</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To__c</fullName>
        <formula>Parent.ENSX_EDM__SAP_Customer_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sold To</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

FusionDev Backup1/src/objects/Deliveries__c.object
<CustomObject>
    <description>Deliveries</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Deliveries (Bill To)</relationshipLabel>
        <relationshipName>Deliveries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ERP_Order__c</fullName>
        <label>Order Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Need_By_Date__c</fullName>
        <label>Need By Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order_Date__c</fullName>
        <formula>Order__r.Order_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Deliveries</relationshipLabel>
        <relationshipName>Deliveries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_Customer_Number__c</fullName>
        <label>SAP Customer Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sent_To_3PL__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent To 3PL</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ship_Date__c</fullName>
        <label>Ship Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ship_To_Party__c</fullName>
        <label>Ship To Party</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Deliveries (Ship To)</relationshipLabel>
        <relationshipName>Deliveries2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipping_Method__c</fullName>
        <label>Shipping Method</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <label>Site</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Deliveries (Sold To)</relationshipLabel>
        <relationshipName>Deliveries1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status_c__c</fullName>
        <label>Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tracking_Number__c</fullName>
        <label>Tracking Number</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Unique_ID__c</fullName>
        <externalId>true</externalId>
        <label>Unique ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Warehouse__c</fullName>
        <label>Warehouse</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Deliveries</label>
    <nameField>
        <label>Pack ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

FusionDev Backup1/src/objects/Delivery_Lines__c.object
<CustomObject>
    <fields>
        <fullName>Deliveries__c</fullName>
        <label>Deliveries</label>
        <referenceTo>Deliveries__c</referenceTo>
        <relationshipLabel>Delivery Lines</relationshipLabel>
        <relationshipName>Delivery_Lines10</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ERP_Order__c</fullName>
        <label>ERP Order</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Change_Time__c</fullName>
        <label>Last Change Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Need_By_Date__c</fullName>
        <label>Need By Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Pack_Line_Num__c</fullName>
        <label>Pack Line Num</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Part_Description__c</fullName>
        <label>Part Description</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Part_Number__c</fullName>
        <label>Part Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QTY_Ordered__c</fullName>
        <label>QTY Ordered</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QTY_Shipped__c</fullName>
        <label>QTY Shipped</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ship_By_Date__c</fullName>
        <label>Ship By Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ship_Via__c</fullName>
        <label>Ship Via</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UOM__c</fullName>
        <label>UOM</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UPC__c</fullName>
        <label>UPC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Warehouse__c</fullName>
        <label>Warehouse</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Delivery Lines</label>
    <nameField>
        <label>Delivery Lines Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FusionDev Backup1/src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Bill_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Need_By_Date__c</fullName>
        <label>Need By Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order_Date__c</fullName>
        <label>Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PurchaseOrder__c</fullName>
        <label>PurchaseOrder</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Customer_Number__c</fullName>
        <label>SAP Customer Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_Via__c</fullName>
        <label>Ship Via</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Sold To)</relationshipLabel>
        <relationshipName>Orders2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

FusionDev Backup1/src/classes/Yeti_PrintShipmentController.cls
/*
Author        :  Rakshit Virmani (Appirio)
Created Date  :  14 March 2017
Name          :  Yeti_PrintShipmentController
Description   :  Controller for Yeti_PrintShipment.page 
Original Task :  T-585055
*/
public with sharing class Yeti_PrintShipmentController {
  public list<Delivery_Lines__c> lstDeliveryLines{get;set;}
  public list<Deliveries__c> lstDeliveries{get;set;}
  public List<String> lstTrackNumList{get;set;}
  private Id shipmentId;
  
  //controls how many quote line items are displayed on page 1
  private static Integer FIRST_BREAK = 9;
  //controls how many quote line items are displayed on subsequent pages
  private static Integer SUBSEQ_BREAKS = 32;
  public List<List<Delivery_Lines__c>> pageBrokenDeliveryLines {get;private set;}
  
  //Constructor 
  public Yeti_PrintShipmentController(){
    lstDeliveryLines = new list<Delivery_Lines__c>();
    lstDeliveries = new list<Deliveries__c>();
    shipmentId = apexpages.currentpage().getparameters().get('id');
    pageBrokenDeliveryLines = new List<List<Delivery_Lines__c>>();
    lstTrackNumList = new List<String>();
    
    if (shipmentId != null){
       lstDeliveries = [SELECT Account__c,Bill_To__c,CreatedById,CreatedDate,ERP_Order__c,Id,IsDeleted,Name,Need_By_Date__c,OwnerId,SAP_Customer_Number__c,Sent_To_3PL__c,
                        Ship_Date__c,Ship_To_Party__c,Ship_To__c,Site__c,Sold_To__c,SystemModstamp,Tracking_Number__c,Unique_ID__c,Warehouse__c,Ship_To__r.ShippingStreet,
                        Ship_To__r.ShippingState,Ship_To__r.ShippingCountry,Ship_To__r.ShippingCity,Ship_To__r.ShippingPostalCode,Order__r.Order_Status__c,Order__r.Order_date__c,
                        Order_Date__c,Sold_To__r.Inside_SR_Name__c,Sold_To__r.Inside_Rep_Phone__c,Sold_To__r.Inside_Rep_Email__c,Sold_To__r.Outside_SR_Name__c,Sold_To__r.Outside_Rep_Phone__c,
                        Sold_To__r.Outside_Rep_Email__c,Status_c__c,Order__r.PurchaseOrder__c,Shipping_Method__c,order__r.Name,
                        (SELECT Deliveries__c,ERP_Order__c,Id, Last_Change_Time__c,Name,Need_By_Date__c,Pack_Line_Num__c,Part_Description__c,Part_Number__c,Quantity__c,
                        Ship_By_Date__c,Ship_Via__c,SystemModstamp,UOM__c,Warehouse__c,QTY_Ordered__c,QTY_Shipped__c,UPC__c FROM Delivery_Lines10__r)
                        FROM Deliveries__c
                        WHERE Id =: shipmentId];
                        
      if(String.isNotBlank(lstDeliveries[0].Tracking_Number__c)) {       List<String> lstString = new List<String>();      lstString = lstDeliveries[0].Tracking_Number__c.split(',');        Integer counter = 0;    for (String st : lstString){      String s = st;         if(math.mod(counter,2) != 0){          s = s + ',' + st;            lstTrackNumList.add(s);}      counter++;}
      }
    }

    if(!lstDeliveries.isEmpty() && !lstDeliveries[0].Delivery_Lines10__r.isEmpty()){
      List<Delivery_Lines__c> lstDeliveriesLines = new List<Delivery_Lines__c>();
        Integer counter = 0;
        boolean firstBreakFound = false;
        boolean setSubSeqBreak = false;       
        Integer breakPoint = FIRST_BREAK;
        
        for(Delivery_Lines__c invLineItem : lstDeliveries[0].Delivery_Lines10__r){
          if(counter <= breakPoint){
            lstDeliveriesLines.add(invLineItem);
            counter++;
          }
          if(counter == breakPoint){         if (!firstBreakFound){       firstBreakFound = true;        setSubSeqBreak = true;        }        counter = 0;        pageBrokenDeliveryLines.add(lstDeliveriesLines);       lstDeliveriesLines = new List<Delivery_Lines__c>();
          }
          if(setSubSeqBreak){        breakPoint = SUBSEQ_BREAKS;        setSubSeqBreak = false;
          }
        }
        if(!lstDeliveriesLines.isEmpty())
          pageBrokenDeliveryLines.add(lstDeliveriesLines);
    
      }
    }
}