FusionDev Backup1/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Inside_Rep_Email__c</fullName>
        <formula>Inside_SR__r.Trading_Post_Email__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Inside Rep Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inside_Rep_Phone__c</fullName>
        <formula>Inside_SR__r.Phone</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Inside Rep Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inside_SR_Name__c</fullName>
        <formula>Inside_SR__r.FirstName + &apos; &apos; + Inside_SR__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Inside Sales Rep</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Outside_Rep_Email__c</fullName>
        <formula>Outside_SR__r.Trading_Post_Email__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>YETI Outside Rep Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Outside_Rep_Phone__c</fullName>
        <formula>Outside_SR__r.Phone</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>YETI Outside Rep Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Outside_SR_Name__c</fullName>
        <formula>Outside_SR__r.FirstName + &apos; &apos; + Outside_SR__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Outside Sales Rep</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To__c</fullName>
        <formula>Parent.ENSX_EDM__SAP_Customer_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sold To</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

FusionDev Backup1/src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Bill_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <label>Discount Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Downgrade__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Downgrade</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EP_Order_Type__c</fullName>
        <label>EP Order Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Free Part</fullName>
                </value>
                <value>
                    <fullName>RMA Replacement</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FOB__c</fullName>
        <label>FOB</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grand_Total__c</fullName>
        <label>Grand Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Line_Total__c</fullName>
        <label>Line Total</label>
        <summarizedField>Order_Line__c.Ext_Price__c</summarizedField>
        <summaryForeignKey>Order_Line__c.Order_Details__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Misc__c</fullName>
        <label>Misc</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Need_By_Date__c</fullName>
        <label>Need By Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Old_Process__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Old Process</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Open_Line_Total__c</fullName>
        <label>Open Line Total</label>
        <summarizedField>Order_Line__c.Ext_Price__c</summarizedField>
        <summaryFilterItems>
            <field>Order_Line__c.Line_Status__c</field>
            <operation>equals</operation>
            <value>Open</value>
        </summaryFilterItems>
        <summaryForeignKey>Order_Line__c.Order_Details__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Open_Line_Unit_Total__c</fullName>
        <label>Open Line Unit Total</label>
        <summarizedField>Order_Line__c.Order_Quantity__c</summarizedField>
        <summaryFilterItems>
            <field>Order_Line__c.Line_Status__c</field>
            <operation>equals</operation>
            <value>Open</value>
        </summaryFilterItems>
        <summaryForeignKey>Order_Line__c.Order_Details__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Order_Comment__c</fullName>
        <label>Order Comment</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Order_Date__c</fullName>
        <label>Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order_Held__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Order Held</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order_Source__c</fullName>
        <label>Order Source</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Subtotal__c</fullName>
        <label>Order Subtotal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Order_Total__c</fullName>
        <label>Order Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Order_Type__c</fullName>
        <label>Order Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PurchaseOrder__c</fullName>
        <label>PurchaseOrder</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RMA_Number__c</fullName>
        <label>RMA Number</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Customer_Number__c</fullName>
        <label>SAP Customer Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_By__c</fullName>
        <label>Ship By</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ship_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ship Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_Via__c</fullName>
        <label>Ship Via</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_Amount__c</fullName>
        <label>Shipping</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Sold To)</relationshipLabel>
        <relationshipName>Orders2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Total__c</fullName>
        <label>Sub Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <label>Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Terms__c</fullName>
        <label>Terms</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Upgrade_Charge__c</fullName>
        <label>Upgrade Charge</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

FusionDev Backup1/src/objects/Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>DiscountPrice__c</fullName>
        <label>DiscountPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Ext_Price__c</fullName>
        <label>Ext Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Last_Change_Date__c</fullName>
        <label>Last Change Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Change_Time__c</fullName>
        <label>Last Change Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Line_Comment__c</fullName>
        <label>Line Comment</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_Number__c</fullName>
        <label>Line Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_Status__c</fullName>
        <label>Line Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Need_By_Date__c</fullName>
        <label>Need By Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Need_By__c</fullName>
        <label>Need By Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order_Details__c</fullName>
        <label>Order Details</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipName>Order_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order_Line__c</fullName>
        <label>Order Line</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <label>Order Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Quantity__c</fullName>
        <label>Order Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Part_Number__c</fullName>
        <label>Part Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Description__c</fullName>
        <label>Product Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <label>Product Group</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Date__c</fullName>
        <label>Request Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sales_Category__c</fullName>
        <label>Sales Category</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_By__c</fullName>
        <label>Ship By</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Shipped__c</fullName>
        <label>Total Shipped</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UPC__c</fullName>
        <label>UPC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Order Line</label>
    <nameField>
        <label>Order Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FusionDev Backup1/src/classes/Yeti_PrintOrderController.cls
/*
Author        :  Rakshit Virmani (Appirio)
Created Date  :  11 March 2017
Name          :  Yeti_PrintOrderController
Description   :  Controller for Yeti_PrintOrder.page 
Original Task :  T-584752
*/
public with sharing class Yeti_PrintOrderController {
  public list<Order_Line__c> lstOrderLines{get;set;}
  public list<Order__c> lstOrders{get;set;}
  private Id orderId;
  public boolean showDiscount{get;set;}
  //controls how many quote line items are displayed on page 1
  private static Integer FIRST_BREAK = 12;
  //controls how many quote line items are displayed on subsequent pages
  private static Integer SUBSEQ_BREAKS = 32;
  public List<List<order_line__c>> pageBrokenOrderLines {get;private set;}
  
  //Constructor 
  public Yeti_PrintOrderController(){
    lstOrderLines = new list<Order_Line__c>();
    lstOrders = new list<Order__c>();
    orderId = apexpages.currentpage().getparameters().get('id');
    showDiscount = false;
    pageBrokenOrderLines = new List<List<order_line__c>>();
    
    if (orderId != null){
       lstOrders =      [SELECT Bill_To__c,Case__c,CreatedById,CreatedDate,Discount_Amount__c,Downgrade__c,EP_Order_Type__c,FOB__c,
                        Id,Line_Total__c,Misc__c,Name,Need_By_Date__c,Old_Process__c,Open_Line_Total__c,Ship_To__r.ShippingStreet,Ship_To__r.ShippingCity,Ship_To__r.ShippingState,
                        Ship_To__r.ShippingCountry,Ship_To__r.ShippingPostalCode,Bill_To__r.BillingStreet,Bill_To__r.BillingCity,Bill_To__r.BillingState,Bill_To__r.BillingCountry,
                        Bill_To__r.BillingPostalCode,Open_Line_Unit_Total__c,Order_Comment__c,Order_Date__c,Order_Held__c,Order_Source__c,Order_Status__c,Order_Subtotal__c,
                        Order_Total__c,Order_Type__c,PurchaseOrder__c,RMA_Number__c,SAP_Customer_Number__c,Ship_By__c,Ship_Complete__c,Ship_To__c,Ship_Via__c,Sold_To__c,Sub_Total__c,
                        Tax__c,Terms__c,Upgrade_Charge__c,Grand_Total__c,Shipping_Amount__c,
                        Sold_To__r.Inside_SR_Name__c,Sold_To__r.Inside_Rep_Phone__c,Sold_To__r.Inside_Rep_Email__c,Sold_To__r.Outside_SR_Name__c,Sold_To__r.Outside_Rep_Phone__c,Sold_To__r.Outside_Rep_Email__c,
                        (SELECT DiscountPrice__c,Ext_Price__c,Last_Change_Date__c,Last_Change_Time__c,Line_Comment__c,Line_Number__c,Line_Status__c,Name,Need_By_Date__c,
                        Need_By__c,Order_Details__c,Order_Line__c,Order_Number__c,Order_Quantity__c,Part_Number__c,Product_Description__c,
                        Product_Group__c,Product__c,Request_Date__c,Sales_Category__c,Ship_By__c,Total_Shipped__c,Unit_Price__c,UPC__c FROM Order_Details__r)
                        FROM Order__c
                        WHERE Id =: orderId];
                        
        if(!lstOrders.isEmpty() && !lstOrders[0].Order_Details__r.isEmpty()){

            List<order_line__c> lstOrderLines = new List<order_line__c>();
            Integer counter = 0;
            boolean firstBreakFound = false;
            boolean setSubSeqBreak = false;       
            Integer breakPoint = FIRST_BREAK;
            
            for(order_line__c invLineItem : lstOrders[0].Order_Details__r){
              if(invLineItem.DiscountPrice__c > 0.00 || invLineItem.DiscountPrice__c < 0.00){
                showDiscount = true;
              }
              if(counter <= breakPoint){
                lstOrderLines.add(invLineItem);
                counter++;
              }
              if(counter == breakPoint){
                if (!firstBreakFound){
                  firstBreakFound = true;
                  setSubSeqBreak = true;
                }
                counter = 0;
                pageBrokenOrderLines.add(lstOrderLines);
                lstOrderLines = new List<order_line__c>();
              }
              if(setSubSeqBreak){
                breakPoint = SUBSEQ_BREAKS;
                setSubSeqBreak = false;
              }
            }
            if(!lstOrderLines.isEmpty())
              pageBrokenOrderLines.add(lstOrderLines);
            }
        }
      }
}