FusionDev Backup1/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ENSX_EDM__SAP_Customer_Number__c</fullName>
        <label>SAP Customer Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

FusionDev Backup1/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Need_By_Date__c</fullName>
        <label>Header Need By Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PO_Number__c</fullName>
        <label>PO Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Account.ParentId</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Account.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Ship To)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

FusionDev Backup1/src/classes/UTIL_YetiQuoteInitializedEventHandler.cls
public class UTIL_YetiQuoteInitializedEventHandler implements I_EventHandler
{
    public void run(Map<String, object> context)
    {
        System.debug('UTIL_YetiQuoteInitializedEventHandler');

        SBO_EnosixQuote_Detail.EnosixQuote quoteDetail =
        (SBO_EnosixQuote_Detail.EnosixQuote) context.get('SBO_EnosixQuote_Detail.EnosixQuote');
        SBO_EnosixQuote_Detail.PARTNERS shippingPartner =
        UTIL_Order.getPartnerFromQuote(quoteDetail, UTIL_Order.SHIP_TO_PARTNER_CODE, true);

        Opportunity opp = (Opportunity) context.get('Opportunity');
        if (opp == null || String.isEmpty(opp.Id))
        {
            return;
        }

        List<Opportunity> customOpps = Database.query('SELECT Ship_To__c, Need_By_Date__c, PO_Number__c '
        + 'FROM Opportunity WHERE Id = \'' + opp.Id + '\' LIMIT 1');

        // Copy custom Yeti fields from Opportunity to Quote.
        if (customOpps.size() > 0)
        {
            Opportunity customOpp = customOpps[0];

            if (null != customOpp.get('Need_By_Date__c'))
            {
                quoteDetail.Sales.RequestedDeliveryDate = (Date) customOpp.get('Need_By_Date__c');
            }

            if (null != customOpp.get('PO_Number__c'))
            {
                quoteDetail.CustomerPurchaseOrderNumber = (String) customOpp.get('PO_Number__c');
            }

            if (null != customOpp.get('Ship_To__c'))
            {
                try
                {
                    List<Account> shipToAccounts = Database.query('SELECT ENSX_EDM__SAP_Customer_Number__c '
                    + 'FROM Account WHERE Id = \'' + customOpp.get('Ship_To__c') + '\' LIMIT 1');
                    if (shipToAccounts.size() > 0)
                    {
                        shippingPartner.CustomerNumber = (String) shipToAccounts[0].get('ENSX_EDM__SAP_Customer_Number__c');
                    }
                }
                catch (Exception ex)
                {
                    ApexPages.addMessages(ex);
                }
            }
        }
    }
}