FusionDev Backup1/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CompanyCode__c</fullName>
        <description>This is defaulted from SAP during the record creation.</description>
        <label>Company Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerNumber__c</fullName>
        <description>Customer Number from SAP</description>
        <inlineHelpText>Customer Number will update once the Account created in SAP</inlineHelpText>
        <label>Customer Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerShipAccount__c</fullName>
        <description>This is a user entered filed, populated during the customer creation.</description>
        <label>Customer Ship Account</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DistributionChannel__c</fullName>
        <description>This data is defaulted from SAP system during customer creation.</description>
        <label>Distribution Channel</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <description>This will be defaulted from SAP system during customer creation.</description>
        <label>Division</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>This is used to capture email during the business account creation.</description>
        <inlineHelpText>Test helptext</inlineHelpText>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>OriginSource__c</fullName>
        <defaultValue>&quot;SalesForce&quot;</defaultValue>
        <description>This field is used to determine the source of the Account/customer during creation.</description>
        <label>Origin Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SalesForce</fullName>
                </value>
                <value>
                    <fullName>SFCC</fullName>
                </value>
                <value>
                    <fullName>SAP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PaymentTerms__c</fullName>
        <description>This field helps to capture the data during customer creation.</description>
        <label>Payment Terms</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PriceList__c</fullName>
        <description>This value is defaulted from SAP system during customer creation.</description>
        <label>Price List</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PriceProcedure__c</fullName>
        <description>This value is defaulted from SAP system during customer creation.</description>
        <label>Price Procedure</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PricingGroup__c</fullName>
        <description>This value is defaulted from SAP system during customer creation.</description>
        <label>Pricing Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesDistrict__c</fullName>
        <description>This value is defaulted from SAP system during customer creation.</description>
        <label>Sales District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesGroup__c</fullName>
        <description>This value is defaulted from SAP system during customer creation.</description>
        <label>Sales Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesOffice__c</fullName>
        <description>This value is defaulted from SAP system during customer creation.</description>
        <label>Sales Office</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesOrg__c</fullName>
        <description>This value is defaulted from SAP during record creation.</description>
        <label>Sales Org</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipToCustomerNumebr__c</fullName>
        <description>This holds the SAP customer number for the ship to Account.</description>
        <label>Ship To Customer Numebr</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShippingCondition__c</fullName>
        <description>This value is defaulted from SAP system during customer creation.</description>
        <label>Shipping Condition</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

FusionDev Backup1/src/classes/SoldToAccount.cls
public class SoldToAccount {
    
    @AuraEnabled
    public static Account getSoldToAccount(Id recId){
        Account acc;
        acc = [SELECT Name, Email__c, Phone,CompanyCode__c, 
                           SalesOrg__c, DistributionChannel__c, Division__c,
                           SalesOffice__c,SalesGroup__c, SalesDistrict__c,
                           PaymentTerms__c,PriceList__c,PricingGroup__c,
                           PriceProcedure__c, ShippingCondition__c,
                           CustomerShipAccount__c,BillingStreet,
                           BillingCity,BillingState,BillingPostalCode,
                           BillingCountry, CustomerNumber__c,CurrencyIsoCode,
               			   ShippingCity,ShippingCountry,ShippingPostalCode,
               			    ShippingState,ShippingStreet,OriginSource__c 
               				FROM Account 
                           WHERE id=: recId LIMIT 1];
        System.debug('Account test Business'+acc);
        return acc;
        
    }
    
    @AuraEnabled
    public static Id saveShipTo(Account ac, Id recId){
       system.debug('accout--'+ac+'--RecId--'+recId);
        String accountRecordTypeName = CommonUtil.getRecordTypeName('Account', 'Ship To', '');     
        Id accRectypeId = RecordTypeSelectionController.getRecTypeIdAccount('Account',accountRecordTypeName,'');
        Account acc = new Account();
        acc = ac;
        acc.ParentId = recId;
        acc.RecordTypeId = accRectypeId;
        String Name = acc.Name;
        String accType = 'ShipTo';
       	String shipToCustomerNumber = AccountService.actuallCallOut(acc,Name,accType);
        if(shipToCustomerNumber !=null && shipToCustomerNumber!='')
        {
            acc.ShipToCustomerNumebr__c = shipToCustomerNumber;
            
            insert acc;
            
        	return acc.Id;
        }
        else 
        {
            return null;
        }
                      
    }

}