FusionDev Backup1/src/objects/Credit_Card__c.object
<CustomObject>
    <description>Account credit cards authorized against Chase Paymentech.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Customer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Credit Cards</relationshipLabel>
        <relationshipName>Credit_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Chase_Profile_Id__c</fullName>
        <externalId>true</externalId>
        <label>Chase Profile Id</label>
        <length>22</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Credit_Card_Name__c</fullName>
        <label>Credit Card Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Number__c</fullName>
        <label>Credit Card Number</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Type__c</fullName>
        <label>Credit Card Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VISA</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>MC</fullName>
                </value>
                <value>
                    <fullName>AMEX</fullName>
                </value>
                <value>
                    <fullName>DISC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Expiration_Month__c</fullName>
        <description>Two digit month</description>
        <label>Expiration Month</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>06</fullName>
                </value>
                <value>
                    <fullName>07</fullName>
                </value>
                <value>
                    <fullName>08</fullName>
                </value>
                <value>
                    <fullName>09</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Expiration_Year__c</fullName>
        <description>Four digit year</description>
        <label>Expiration Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2014</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Send_To_ERP__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Send To ERP</label>
        <type>Checkbox</type>
    </fields>
    <label>Credit Card</label>
    <nameField>
        <displayFormat>CC-{00000}</displayFormat>
        <label>Credit Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Cards</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

FusionDev Backup1/src/objects/Credit_Card_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Allow_Multiple_Cards__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Allow Multiple Cards</label>
        <type>Checkbox</type>
    </fields>
    <label>Credit Card Settings</label>
</CustomObject>

FusionDev Backup1/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Chase_Profile_Id__c</fullName>
        <label>Chase Profile Id</label>
        <length>22</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Expiration_Month__c</fullName>
        <label>Credit Card Expiration Month</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>06</fullName>
                </value>
                <value>
                    <fullName>07</fullName>
                </value>
                <value>
                    <fullName>08</fullName>
                </value>
                <value>
                    <fullName>09</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credit_Card_Expiration_Year__c</fullName>
        <label>Credit Card Expiration Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
                <value>
                    <fullName>2026</fullName>
                </value>
                <value>
                    <fullName>2027</fullName>
                </value>
                <value>
                    <fullName>2028</fullName>
                </value>
                <value>
                    <fullName>2029</fullName>
                </value>
                <value>
                    <fullName>2030</fullName>
                </value>
                <value>
                    <fullName>2031</fullName>
                </value>
                <value>
                    <fullName>2032</fullName>
                </value>
                <value>
                    <fullName>2033</fullName>
                </value>
                <value>
                    <fullName>2034</fullName>
                </value>
                <value>
                    <fullName>2035</fullName>
                </value>
                <value>
                    <fullName>2036</fullName>
                </value>
                <value>
                    <fullName>2037</fullName>
                </value>
                <value>
                    <fullName>2038</fullName>
                </value>
                <value>
                    <fullName>2039</fullName>
                </value>
                <value>
                    <fullName>2040</fullName>
                </value>
                <value>
                    <fullName>2041</fullName>
                </value>
                <value>
                    <fullName>2042</fullName>
                </value>
                <value>
                    <fullName>2043</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credit_Card_Name__c</fullName>
        <label>Credit Card Name</label>
        <length>54</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Number__c</fullName>
        <label>Credit Card Number</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Type__c</fullName>
        <label>Credit Card Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VISA</fullName>
                </value>
                <value>
                    <fullName>MC</fullName>
                </value>
                <value>
                    <fullName>AMEX</fullName>
                </value>
                <value>
                    <fullName>DISC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credit_Card__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Credit Card</label>
        <referenceTo>Credit_Card__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <label>Sales Order</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_To_ERP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send To ERP</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

FusionDev Backup1/src/classes/CreditCardUtil.cls
/*
* -----------------------------------------------------------
* Apex Class Name: CreditCardUtil
* -----------------------------------------------------------
* Description: This class contains methods to peform operations
* assoicated with the CreditCard and related objects.
* -----------------------------------------------------------
* Created by: Jeff Rogers, Alternative Technology Solutions.
* Created on: 20134-10-23
* Last Modified by: 
* Last Date Modified:
* Modification Log:
* 1 - 
*/

public class CreditCardUtil{
	
	private static final Credit_Card_Settings__c settings = Credit_Card_Settings__c.getOrgDefaults();
    
    //The updateOpps method updates pending opportunties with new credit card info
	//Trigger Context: After Insert, After Update
    public static void updateOpps(List<Credit_Card__c> creditCards, Map<Id,Credit_Card__c> oldCCMap) {

    	//only process if multiple active credit cards are not allowed
    	if (!settings.Allow_Multiple_Cards__c) {
	    	
    		Map<Id,Credit_Card__c> accountToActiveProfiles = new Map<Id,Credit_Card__c>();
    		Set<String> activeProfileIds = new Set<String>();
	    	Set<Id> accountIds = new Set<Id>();
	    	
	    	for (Credit_Card__c cc: creditCards) {
	    	//handle inserted credit cards
		    	if (oldCCMap == null) {
	    			if (cc.Active__c) {
	    				accountToActiveProfiles.put(cc.Account__c, cc);
	    				activeProfileIds.add(cc.Chase_Profile_Id__c);
	    				accountIds.add(cc.Account__c);
	    			}
		    	}
		    	//handle updated credit cards
		    	else {
	    			if ((cc.Active__c && !oldCCMap.get(cc.Id).Active__c) || (cc.Credit_Card_Name__c != oldCCMap.get(cc.Id).Credit_Card_Name__c) || (cc.Expiration_Year__c != oldCCMap.get(cc.Id).Expiration_Year__c) || (cc.Expiration_Month__c != oldCCMap.get(cc.Id).Expiration_Month__c)) {
	    				accountToActiveProfiles.put(cc.Account__c, cc);
	    				activeProfileIds.add(cc.Chase_Profile_Id__c);
	    				accountIds.add(cc.Account__c);
	    			}
		    	}
	    	}
	    	
	    	//update opps
	    	List<Opportunity> oppsToUpdate = [SELECT Id, AccountId, Chase_Profile_Id__c, Credit_Card__c, Credit_Card_Type__c, Credit_Card_Number__c, Credit_Card_Name__c, Credit_Card_Expiration_Year__c, Credit_Card_Expiration_Month__c FROM Opportunity WHERE AccountId IN : accountIds AND Chase_Profile_Id__c != '' AND Send_To_ERP__c = false AND Sales_Order__c = ''];
	    	for (Opportunity o : oppsToUpdate) {
	    		if (accountToActiveProfiles.containsKey(o.AccountId)) {
	    			o.Credit_Card__c = accountToActiveProfiles.get(o.AccountId).Id;
	    			o.Chase_Profile_Id__c = accountToActiveProfiles.get(o.AccountId).Chase_Profile_Id__c;
	    			o.Credit_Card_Type__c = accountToActiveProfiles.get(o.AccountId).Credit_Card_Type__c;
	    			o.Credit_Card_Number__c = accountToActiveProfiles.get(o.AccountId).Credit_Card_Number__c.right(4);
	    			o.Credit_Card_Name__c = accountToActiveProfiles.get(o.AccountId).Credit_Card_Type__c;
	    			o.Credit_Card_Expiration_Year__c = accountToActiveProfiles.get(o.AccountId).Expiration_Year__c;
	    			o.Credit_Card_Expiration_Month__c = accountToActiveProfiles.get(o.AccountId).Expiration_Month__c;
	    		}
	    	}
	    	
	    	if (!oppsToUpdate.isEmpty()) {
	    		update oppsToUpdate;
	    	}
    	}
    	
    }
    
    
    //The deactivateCCs method updates existing cards when a new active card is inserted (and multiple active cards are not allowed)
	//Trigger Context: After Insert
    public static void deactivateCCs() {

    	//only process if multiple active credit cards are not allowed
    	if (!settings.Allow_Multiple_Cards__c) {
    		/*
    		Map<Id,List<Credit_Card__c>> accountIdToCreditCards = new Map<Id,List<Credit_Card__c>>();
    		Set<Id> accountIds = new Set<Id>();
    		for (Credit_Card__c cc : creditCards) {
    			accountIds.add(cc.Account__c);
    		}*/
    		
    		//get accounts with multiple active cards
    		Set<Id> accountIds = new Set<Id>();
    		List<AggregateResult> ar = [SELECT Account__c, Count(Id) FROM Credit_Card__c WHERE Active__c = true GROUP BY Account__c HAVING Count(Id) > 1];
    		for (AggregateResult result : ar) {
    			accountIds.add(String.valueOf(result.get('Account__c')));
    		}
    		
    		//get credit cards to deactiveate (order by chase profile id DESC so we do not deactive the first/newest)
    		Id accountId;
    		List<Credit_Card__c> creditCards = [SELECT Id, Account__c, Chase_Profile_Id__c, Active__c FROM Credit_Card__c WHERE Account__c IN : accountIds AND Active__c = true ORDER BY Account__c, Chase_Profile_Id__c DESC];
    		List<Credit_Card__c> ccsToDeactivate = new List<Credit_Card__c>();
    		for (Credit_Card__c cc : creditCards) {
    			if (cc.Account__c == accountId) {
    				cc.Active__c = false;
    				ccsToDeactivate.add(cc);
    			}
    			accountId = cc.Account__c;
    		}
    		
    		if (!ccsToDeactivate.isEmpty()) {
    			update ccsToDeactivate;
    		}
    	}
    	
    }
    
    
    public static string maskCard(Credit_Card__c card) {
		
    	String ccNum;
    	
		if (card.Credit_Card_Type__c == 'AMEX') {
			ccNum = '***********' + card.Credit_Card_Number__c.right(4);
		}
		else {
			ccNum = '************' + card.Credit_Card_Number__c.right(4);
		}
		
		return ccNum;
		
	}
    
}