FusionDev Backup1/src/objects/Credit_Card__c.object
<CustomObject>
    <description>Account credit cards authorized against Chase Paymentech.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Customer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Credit Cards</relationshipLabel>
        <relationshipName>Credit_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Address1__c</fullName>
        <label>Address1</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address2__c</fullName>
        <label>Address2</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Chase_Profile_Id__c</fullName>
        <externalId>true</externalId>
        <label>Chase Profile Id</label>
        <length>22</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>US</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>GB</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credit_Card_Name__c</fullName>
        <label>Credit Card Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Number__c</fullName>
        <label>Credit Card Number</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Type__c</fullName>
        <label>Credit Card Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VISA</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>MC</fullName>
                </value>
                <value>
                    <fullName>AMEX</fullName>
                </value>
                <value>
                    <fullName>DISC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Expiration_Month__c</fullName>
        <description>Two digit month</description>
        <label>Expiration Month</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>06</fullName>
                </value>
                <value>
                    <fullName>07</fullName>
                </value>
                <value>
                    <fullName>08</fullName>
                </value>
                <value>
                    <fullName>09</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Expiration_Year__c</fullName>
        <description>Four digit year</description>
        <label>Expiration Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2014</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Credit Card</label>
    <nameField>
        <displayFormat>CC-{00000}</displayFormat>
        <label>Credit Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Cards</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

FusionDev Backup1/src/objects/Credit_Card_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Allow_Multiple_Cards__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Allow Multiple Cards</label>
        <type>Checkbox</type>
    </fields>
    <label>Credit Card Settings</label>
</CustomObject>

FusionDev Backup1/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Chase_Profile_Id__c</fullName>
        <label>Chase Profile Id</label>
        <length>22</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Expiration_Year__c</fullName>
        <label>Credit Card Expiration Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
                <value>
                    <fullName>2026</fullName>
                </value>
                <value>
                    <fullName>2027</fullName>
                </value>
                <value>
                    <fullName>2028</fullName>
                </value>
                <value>
                    <fullName>2029</fullName>
                </value>
                <value>
                    <fullName>2030</fullName>
                </value>
                <value>
                    <fullName>2031</fullName>
                </value>
                <value>
                    <fullName>2032</fullName>
                </value>
                <value>
                    <fullName>2033</fullName>
                </value>
                <value>
                    <fullName>2034</fullName>
                </value>
                <value>
                    <fullName>2035</fullName>
                </value>
                <value>
                    <fullName>2036</fullName>
                </value>
                <value>
                    <fullName>2037</fullName>
                </value>
                <value>
                    <fullName>2038</fullName>
                </value>
                <value>
                    <fullName>2039</fullName>
                </value>
                <value>
                    <fullName>2040</fullName>
                </value>
                <value>
                    <fullName>2041</fullName>
                </value>
                <value>
                    <fullName>2042</fullName>
                </value>
                <value>
                    <fullName>2043</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credit_Card_Name__c</fullName>
        <label>Credit Card Name</label>
        <length>54</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Number__c</fullName>
        <label>Credit Card Number</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Type__c</fullName>
        <label>Credit Card Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VISA</fullName>
                </value>
                <value>
                    <fullName>MC</fullName>
                </value>
                <value>
                    <fullName>AMEX</fullName>
                </value>
                <value>
                    <fullName>DISC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credit_Card__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Credit Card</label>
        <referenceTo>Credit_Card__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

FusionDev Backup1/src/classes/CreditCardEntryCon.cls
public class CreditCardEntryCon {
	
	private ApexPages.StandardController sc;	
	private static final Credit_Card_Settings__c settings = Credit_Card_Settings__c.getOrgDefaults();
	public Id oppId;
	public Credit_Card__c creditCard {get;set;}
	public List<Credit_Card__c> creditCards {get;set;}
	public Boolean activeCards {get;set;}
	public Boolean multCardsAllowed {get;set;}
	public Boolean editMode {get;set;}
	public Boolean fromOpp {get;set;}
	public Boolean saveToAccount {get;set;}

	public CreditCardEntryCon(ApexPages.StandardController controller) {
		
		//controller and misc field setup (need to add fields for edit mode)
		List<String> fieldsToAdd = new List<String>{'Account__c', 'Chase_Profile_Id__c', 'Active__c', 'Address1__c', 'Address2__c', 'City__c', 'Country__c', 'Credit_Card_Name__c', 'Credit_Card_Number__c', 'Credit_Card_Type__c', 'Email__c', 'Expiration_Month__c', 'Expiration_Year__c', 'Phone__c', 'State__c', 'Zip__c'};
		this.sc = controller;
		multCardsAllowed = settings.Allow_Multiple_Cards__c;
		
		if (!Test.isRunningTest()) {
			this.sc.addFields(fieldsToAdd);
		}
		creditCard = (Credit_Card__c)controller.getRecord();
		
		//edit credit card?
		if (ApexPages.currentPage().getParameters().get('Id') != null) {
			editMode = true;
			read();
		}
		else {
			editMode = false;
		}
		
		//add new credit card from Opp?
		if (ApexPages.currentPage().getParameters().get('oppId') != null) {
			fromOpp = true;
			oppId = ApexPages.currentPage().getParameters().get('oppId');
		}
		else {
			fromOpp = false;
		}
		
		//any active cards?
		activeCards = false;
		creditCards = [SELECT Chase_Profile_Id__c, Active__c, Id FROM Credit_Card__c WHERE Account__c =: creditCard.Account__c AND Active__c = true];
		if (!creditCards.isEmpty()) {
			activeCards = true;
		}
		
		//hardcode data - country, active (if only one card is allowed)
		if(creditCard.Country__c == '' || creditCard.Country__c == null) {
			creditCard.Country__c = 'US';
		}
		
	}
	
	public PageReference addCard() {
		
		try {
			//set card to active
			creditCard.Active__c = true;
			
			//return and display errors if input validation fails
			if(!validInput('C')) {
				return null;
			}
			
			//add profile
			String result = OrbitalGateway.profileRequest(creditCard, 'C', 'Y');
			
			//display gateway error if any
			if (result <> 'success') {
				creditCard.addError(result);
				return null;
			}
			
			saveCardToAccount('C');
				
			return new PageReference('/' + creditCard.Account__c);
			
		}
		
		catch (Exception e) {
			ApexPages.addMessages(e);
			return null;
		}
		
	}
	
	public PageReference updateCard() {
		
		try {
			//return and display errors if input validation fails
			if(!validInput('U')) {
				return null;
			}
			
			//update profile
			String result = OrbitalGateway.profileRequest(creditCard, 'U', 'Y');
			
			//display gateway error if any
			if (result <> 'success') {
				creditCard.addError(result);
				return null;
			}
			
			saveCardToAccount('U');
				
			return new PageReference('/' + creditCard.Account__c);
			
		}
		
		catch (Exception e) {
				ApexPages.addMessages(e);
				return null;
		}
		
	}
	
	public PageReference addCardFromOpp() {
		
		try {
			//return and display errors if input validation fails
			if(!validInput('C')) {
				return null;
			}
			
			//add profile
			String result = OrbitalGateway.profileRequest(creditCard, 'C', 'N');
			
			//display gateway error if any
			if (result <> 'success') {
				creditCard.addError(result);
				return null;
			}
				
			Opportunity o = new Opportunity(Id = oppId, Chase_Profile_Id__c = creditCard.Chase_Profile_Id__c, Credit_Card_Type__c = creditCard.Credit_Card_Type__c, Credit_Card_Number__c = creditCard.Credit_Card_Number__c.right(4), Credit_Card_Name__c = creditCard.Credit_Card_Name__c, Credit_Card_Expiration_Year__c = creditCard.Expiration_Year__c, Credit_Card_Expiration_Month__c = creditCard.Expiration_Month__c);
			update o;
			return new PageReference('/' + oppId);
			
		}
		
		catch (Exception e) {
				ApexPages.addMessages(e);
				return null;
		}
		
		
	}
	
	public PageReference addCardFromOppAndSave() {
		
		
		try {
			//return and display errors if input validation fails
			if(!validInput('C')) {
				return null;
			}
			
			//add profile
			String result = OrbitalGateway.profileRequest(creditCard, 'C', 'Y');
			
			//display gateway error if any
			if (result <> 'success') {
				creditCard.addError(result);
				return null;
			}
			
			Id creditCardId = saveCardToAccount('C');
				
			Opportunity o = new Opportunity(Id = oppId, Credit_Card__c = creditCardId, Chase_Profile_Id__c = creditCard.Chase_Profile_Id__c, Credit_Card_Type__c = creditCard.Credit_Card_Type__c, Credit_Card_Number__c = creditCard.Credit_Card_Number__c.right(4), Credit_Card_Name__c = creditCard.Credit_Card_Name__c, Credit_Card_Expiration_Year__c = creditCard.Expiration_Year__c, Credit_Card_Expiration_Month__c = creditCard.Expiration_Month__c);
			update o;
			return new PageReference('/' + oppId);
			
		}
		
		catch (Exception e) {
			ApexPages.addMessages(e);
			return null;
		}
		
	}
	
	private Id saveCardToAccount(String modType) {
		
		//clone to prevent fields from being cleared if validations stop save
		Credit_Card__c ccToUpsert = creditCard.clone();
		
		ccToUpsert.Credit_Card_Number__c = CreditCardUtil.maskCard(ccToUpsert);
		
		//clear specific fields (retreived from Chase later when needed)
		ccToUpsert.Address1__c = '';
		ccToUpsert.Address2__c = '';
		ccToUpsert.City__c = '';
		ccToUpsert.State__c = '';
		ccToUpsert.Zip__c = '';
		ccToUpsert.Country__c = '';
		ccToUpsert.Email__c = null;
		ccToUpsert.Phone__c = '';
		ccToUpsert.Security_Code__c = null;
		
		//insert SF credit card record and deactive other card if needed
		List<Credit_Card__c> ccsToUpsert = new List<Credit_Card__c>();
		ccsToUpsert.add(ccToUpsert);
		
		if (!multCardsAllowed && activeCards && modType == 'C') {
			for (Credit_Card__c cc : creditCards) {
				if (cc.Active__c && cc.Chase_Profile_Id__c != ccToUpsert.Chase_Profile_Id__c) {
					cc.Active__c = false;
					ccsToUpsert.add(cc);
				}
			}
		}
		upsert ccsToUpsert Chase_Profile_Id__c;
		
		Id creditCardId = [SELECT Id FROM Credit_Card__c WHERE Chase_Profile_Id__c = : ccToUpsert.Chase_Profile_Id__c LIMIT 1].Id;
		
		return creditCardId;
		
	}
	
	public PageReference cancel() {
		if (oppId != null) {
			return new PageReference('/' + oppId);
		}
		else {
			return new PageReference('/' + creditCard.Account__c);
		}
	}
	
	private void read() {
		
		try {
			
			//read profile
			String result = OrbitalGateway.profileRequest(creditCard, 'R', '');
			
			//display gateway error if any
			if (result <> 'success') {
				ApexPages.Message message = new ApexPages.Message(ApexPages.Severity.ERROR, result);
				ApexPages.addMessage(message);
			}
			
		}
		
		catch (Exception e) {
			ApexPages.addMessages(e);
		}
		
	}
	
	private Boolean validInput(String modType) {
		
		Boolean validNum = true;
		Boolean validExp = true;
		Boolean validSecCode = true;//validSecCode();
		Boolean validZip = true;
		
		if (modType <> 'U') {
			validNum = validNum();
		}
		
		validExp = validExp();
		validSecCode = true;//validSecCode();
		validZip = validZip();
		
		if (!validNum || !validExp || !validSecCode || !validZip) {
			return false;
		}
		else {
			return true;
		}
		
		
	}
	
	private Boolean validNum() {
		
		Boolean validResults = true;
		
		if (creditCard.Credit_Card_Type__c == 'AMEX' && (creditCard.Credit_Card_Number__c.substring(0,1) <> '3' || creditCard.Credit_Card_Number__c.length() <> 15)) {
			creditCard.Credit_Card_Number__c.addError ('Enter a valid 15 digit AMEX credit card number');
			validResults = false;
		}
		else if (creditCard.Credit_Card_Type__c == 'VISA' && (creditCard.Credit_Card_Number__c.substring(0,1) <> '4' || creditCard.Credit_Card_Number__c.length() <> 16)) {
			creditCard.Credit_Card_Number__c.addError ('Enter a valid 16 digit Visa credit card number');
			validResults = false;
		}
		else if (creditCard.Credit_Card_Type__c == 'MC' && (creditCard.Credit_Card_Number__c.substring(0,1) <> '5' || creditCard.Credit_Card_Number__c.length() <> 16)) {
			creditCard.Credit_Card_Number__c.addError ('Enter a valid 16 digit Mastercard credit card number');
			validResults = false;
		}
		else if (creditCard.Credit_Card_Type__c == 'DISC' && (creditCard.Credit_Card_Number__c.substring(0,1) <> '6' || creditCard.Credit_Card_Number__c.length() <> 16)) {
			creditCard.Credit_Card_Number__c.addError ('Enter a valid 16 digit Discover credit card number');
			validResults = false;
		}
		
		return validResults;
	}
	
	private Boolean validExp() {
		
		Boolean validResults = true;
		
		if (Integer.valueOf(creditCard.Expiration_Year__c) < System.today().year()) {
			creditCard.Expiration_Year__c.addError ('Enter a valid year');
			validResults = false;
		}
		else if (Integer.valueOf(creditCard.Expiration_Year__c) == System.today().year() && Integer.valueOf(creditCard.Expiration_Month__c) < System.today().month()) {
			creditCard.Expiration_Month__c.addError ('Enter a valid month');
			validResults = false;
		}
		
		return validResults;

	}
	
	/*
	private Boolean validSecCode() {
		Boolean validResults = true;
		
		if ((creditCard.Credit_Card_Type__c == 'VISA' || creditCard.Credit_Card_Type__c == 'MC' || creditCard.Credit_Card_Type__c == 'DISC') && creditCard.Security_Code__c < 100) {
			creditCard.Security_Code__c.addError ('Enter a valid 3 digit security code');
			validResults = false;
		}
		else if (creditCard.Credit_Card_Type__c == 'AMEX' && creditCard.Security_Code__c < 1000) {
			creditCard.Security_Code__c.addError ('Enter a valid 4 digit security code');
			validResults = false;
		}
		
		return validResults;
	}*/
	
	private Boolean validZip() {
		Boolean validResults = true;
		
		if (!creditCard.Zip__c.isNumeric() || creditCard.Zip__c.length() <> 5) {
			creditCard.Zip__c.addError ('Enter a valid 5 digit zip');
			validResults = false;
		}
		
		return validResults;
	}
	
}