FusionDev Backup1/src/objects/Credit_Card__c.object
<CustomObject>
    <description>Account credit cards authorized against Chase Paymentech.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Customer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Credit Cards</relationshipLabel>
        <relationshipName>Credit_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Chase_Profile_Id__c</fullName>
        <externalId>true</externalId>
        <label>Chase Profile Id</label>
        <length>22</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Credit_Card_Name__c</fullName>
        <label>Credit Card Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Number__c</fullName>
        <label>Credit Card Number</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Type__c</fullName>
        <label>Credit Card Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VISA</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>MC</fullName>
                </value>
                <value>
                    <fullName>AMEX</fullName>
                </value>
                <value>
                    <fullName>DISC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Expiration_Month__c</fullName>
        <description>Two digit month</description>
        <label>Expiration Month</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>06</fullName>
                </value>
                <value>
                    <fullName>07</fullName>
                </value>
                <value>
                    <fullName>08</fullName>
                </value>
                <value>
                    <fullName>09</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Expiration_Year__c</fullName>
        <description>Four digit year</description>
        <label>Expiration Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2014</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Expired__c</fullName>
        <formula>IF(OR(ISPICKVAL(Expiration_Year__c,&quot;&quot;),ISPICKVAL(Expiration_Month__c,&quot;&quot;),VALUE(&quot;20&quot;+TEXT(Expiration_Year__c)) &lt; YEAR(TODAY()), AND(VALUE(&quot;20&quot;+TEXT(Expiration_Year__c)) = YEAR(TODAY()),VALUE(TEXT(Expiration_Month__c)) &lt; MONTH(TODAY()))),TRUE, FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <label>Credit Card</label>
    <nameField>
        <displayFormat>CC-{00000}</displayFormat>
        <label>Credit Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Cards</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

FusionDev Backup1/src/objects/Credit_Card_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Allow_Multiple_Cards__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Allow Multiple Cards</label>
        <type>Checkbox</type>
    </fields>
    <label>Credit Card Settings</label>
</CustomObject>

FusionDev Backup1/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Chase_Profile_Id__c</fullName>
        <label>Chase Profile Id</label>
        <length>22</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Expiration_Month__c</fullName>
        <label>Credit Card Expiration Month</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>06</fullName>
                </value>
                <value>
                    <fullName>07</fullName>
                </value>
                <value>
                    <fullName>08</fullName>
                </value>
                <value>
                    <fullName>09</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credit_Card_Expiration_Year__c</fullName>
        <label>Credit Card Expiration Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
                <value>
                    <fullName>2026</fullName>
                </value>
                <value>
                    <fullName>2027</fullName>
                </value>
                <value>
                    <fullName>2028</fullName>
                </value>
                <value>
                    <fullName>2029</fullName>
                </value>
                <value>
                    <fullName>2030</fullName>
                </value>
                <value>
                    <fullName>2031</fullName>
                </value>
                <value>
                    <fullName>2032</fullName>
                </value>
                <value>
                    <fullName>2033</fullName>
                </value>
                <value>
                    <fullName>2034</fullName>
                </value>
                <value>
                    <fullName>2035</fullName>
                </value>
                <value>
                    <fullName>2036</fullName>
                </value>
                <value>
                    <fullName>2037</fullName>
                </value>
                <value>
                    <fullName>2038</fullName>
                </value>
                <value>
                    <fullName>2039</fullName>
                </value>
                <value>
                    <fullName>2040</fullName>
                </value>
                <value>
                    <fullName>2041</fullName>
                </value>
                <value>
                    <fullName>2042</fullName>
                </value>
                <value>
                    <fullName>2043</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credit_Card_Name__c</fullName>
        <label>Credit Card Name</label>
        <length>54</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Number__c</fullName>
        <label>Credit Card Number</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Type__c</fullName>
        <label>Credit Card Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VISA</fullName>
                </value>
                <value>
                    <fullName>MC</fullName>
                </value>
                <value>
                    <fullName>AMEX</fullName>
                </value>
                <value>
                    <fullName>DISC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credit_Card__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Credit Card</label>
        <referenceTo>Credit_Card__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

FusionDev Backup1/src/classes/CreditCardSelectCon.cls
public class CreditCardSelectCon {
	
	private ApexPages.StandardController sc;
	public Opportunity opp {get;set;}
	public List<Wrapper> wrappers {get;set;}
	public Boolean allowEntry {get;set;}
	private static final Credit_Card_Settings__c settings = Credit_Card_Settings__c.getOrgDefaults();
	public Id clickedCCId {get;set;}
	public Id accountid {get;set;}

	public CreditCardSelectCon(ApexPages.StandardController controller) {
		
		system.debug('In Controller constructor');
		
		this.sc = controller;
		allowEntry = true;
		
		opp = (Opportunity)controller.getRecord();
		accountId = [SELECT AccountId FROM Opportunity WHERE Id =: opp.Id].AccountId;
		wrappers = new List<Wrapper>();
		for (Credit_Card__c cc : [SELECT Id, Chase_Profile_Id__c, Credit_Card_Type__c, Credit_Card_Number__c, Credit_Card_Name__c, Expiration_Month__c, Expiration_Year__c FROM Credit_Card__c WHERE Active__c = true AND Expired__c = false AND Account__c =: accountId ORDER BY Credit_Card_Type__c]) {
			Wrapper w = new Wrapper(cc);
			wrappers.add(w);
		}
		if (wrappers.isEmpty()) {
			ApexPages.Message message = new ApexPages.Message(ApexPages.Severity.INFO, 'No Available credit cards, please enter new card');
			ApexPages.addMessage(message);
		}
		if (!settings.Allow_Multiple_Cards__c && !wrappers.isEmpty()) {
			allowEntry = false;
		}
	}
	
	public void unSelectCC() {
		for(Wrapper w : wrappers) {
			if (w.selected && w.creditCard.Id <> clickedCCId) {
				w.selected = false;
			}
		}
	}
	
	
	public PageReference onContinue(){
		
		//get selected credit card id
		Id ccId;
		String ccProfileId;
		String ccNum;
		String ccType;
		String ccMonth;
		String ccYear;
		
		for (Wrapper w : wrappers) {
			if (w.selected) {
				ccId = w.creditCard.Id;
				ccProfileId = w.creditCard.Chase_Profile_Id__c;
				ccNum = w.creditCard.Credit_Card_Number__c.right(4);
				ccType = w.creditCard.Credit_Card_Type__c;
				ccMonth = w.creditCard.Expiration_Month__c;
				ccYear = w.creditCard.Expiration_Year__c;
				break;
			}
		}
		
		//if none selected throw error
		if (ccId == null) {
			ApexPages.Message message = new ApexPages.Message(ApexPages.Severity.ERROR, 'Please select a credit card before continuing');
			ApexPages.addMessage(message);
			return null;
		}
		
		//update opp with selected credit card
		opp.Credit_Card__c = ccId;
		opp.Chase_Profile_Id__c = ccProfileId;
		opp.Credit_Card_Number__c = ccNum;
		opp.Credit_Card_Type__c = ccType;
		opp.Credit_Card_Name__c = 
		opp.Credit_Card_Expiration_Month__c = ccMonth;
		opp.Credit_Card_Expiration_Year__c = ccYear;

		try {
			update opp;
		}
		catch (Exception e) {
			ApexPages.addMessages(e);
			return null;
		}
		
		return new PageReference('/' + opp.Id);
		
	}
	
	//this method will need to be updated to only use productions accountId element Id when the sandboxes are refreshed
	public PageReference onNew() {
		string acctIdParam;
		if (URL.getSalesforceBaseUrl().getHost().left(4).equalsignorecase('c.cs')) {
			acctIdParam = 'CF00N19000000GPbb_lkid'; //BackupProd
			//acctIdParam = 'CF00N19000000GA9x_lkid'; //Dev
		}
		else {
			acctIdParam = 'CF00Ni000000FUGTm_lkid'; //Production
		}
		return new PageReference('/apex/addCreditCard?' + acctIdParam + '=' + accountId + '&scontrolCaching=1&sfdc.override=1&oppId=' + opp.Id);
	}
	
	
	Public class Wrapper {
		public Credit_Card__c creditCard {get;set;}
		public Boolean selected {get;set;}
		
		public Wrapper(Credit_Card__c cc) {
			system.debug('In wrapper constructor');
			this.creditCard = cc;
			this.selected = false;
		}
	}
	
}