FusionDev Backup1/src/objects/EmbellishedArt__c.object
<CustomObject>
    <description>This Object holds the design records with a set of values which are to be defined before the design has to be released to SAP as a material.</description>
    <fields>
        <fullName>WebKey__c</fullName>
        <description>This formula generates the Web Key for the s3 service based on the values captured in the entry fields.</description>
        <formula>IF(ISBLANK( TEXT(IsPremium__c) ) , &quot;//&quot;, IF( TEXT(IsPremium__c) = &quot;Yes&quot;, &quot;/premium/&quot;, &quot;/standard/&quot;)) &amp; LOWER(TEXT(Category__c)) &amp; &quot;/&quot;  &amp; LOWER(ArtYETIKey__c)</formula>
        <label>Web Key</label>
        <type>Text</type>
    </fields>
    <label>Embellished Art</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Embellished Art</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Embellished Arts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FusionDev Backup1/src/objects/EmbellishedProduct__c.object
<CustomObject>
    <description>A design is always coupled, or applied to, a customized product.  So a design is often not useful on it&apos;s own; you need to know what customized product it&apos;s being applied to to understand specifically how the art of a given design should be.</description>
    <fields>
        <fullName>ProductName__c</fullName>
        <description>The name of the embellished product. This is an internal name; not displayed to customers.</description>
        <inlineHelpText>Format : [Alphanumeric] [Alphanumeric].. [Alphanumeric].</inlineHelpText>
        <label>Product Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ProductYETIKey__c</fullName>
        <description>Generically put, this is a key which uniquely defines this design in all systems.  Specifically, this is needed by SFCC to identify the cup against the Art Gallery.  Also, this value is also used in APIs for images, as well as constructing well-known paths against Amazon S3.    More discussion can be found here: Universal Product Key (UPK)</description>
        <inlineHelpText>One must strictly enter only alphanumeric characters or a hyphen. 
Note : No multiple hyphens &apos; --&apos; or a space between words. 
Format : [Text/Numeric]-[Text/Numeric]</inlineHelpText>
        <label>YETI Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Embellished Product</label>
    <nameField>
        <displayFormat>EP-{0000}</displayFormat>
        <label>Embellished Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Embellished Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FusionDev Backup1/src/classes/ArtDesignController.cls
/*
######################################################################################################################
Name:       ArtDesignController.apxc 
Description:  This class contain method to return the list 
S.NO:     Date      Version      Author             Summary of Changes 
**********************************************************************************************************************
  1     4/12/2018    1.0       Ranjith Thadakala      Initial Release
**********************************************************************************************************************
*/
public with sharing class ArtDesignController{
       


 /*wrapper class*/
 public with sharing class ArtDesignWrapper {

  @AuraEnabled public string productName{get;set;}
  @AuraEnabled public string laser{get;set;}
  @AuraEnabled public string laserback{get;set;}
  @AuraEnabled public string front {get;set;}
  @AuraEnabled public string back {get;set;}
    
}
 
/*
######################################################################################################################
Method Name:       getProducts
Description:  This methods returns the product urls for the Art images.
S.NO:     Date      Version      Author             Summary of Changes 
**********************************************************************************************************************
  1     4/12/2018    1.0       Ranjith Thadakala      Initial Release
**********************************************************************************************************************
*/
    @AuraEnabled
    public static List<ArtDesignWrapper>  getProducts(Id recordId){
     try{
       List<ArtDesignWrapper> wrapList = new List<ArtDesignWrapper>(); 
       List<EmbellishedProduct__c> EmbPrdtList = [select ProductName__c, ProductYETIKey__c from EmbellishedProduct__c  ];
       string Webkey = [select WebKey__c from EmbellishedArt__c where id =: recordId limit 1].WebKey__c;
       string Url = CommonUtil.getCommonMetaData('AmazonUrl')+ Webkey +'/';
       ArtDesignWrapper wrpObj;
       for(EmbellishedProduct__c embobj : EmbPrdtList ){	
            wrpObj = new ArtDesignWrapper();
            wrpObj.productName = embobj.ProductName__c;
            wrpObj.laser= Url+ embobj.ProductYETIKey__c +'/'+ CommonUtil.getCommonMetaData('Laser');
            wrpObj.laserback = Url+ embobj.ProductYETIKey__c +'/'+ CommonUtil.getCommonMetaData('LaserReady');
            wrpObj.front = Url+ embobj.ProductYETIKey__c +'/'+ CommonUtil.getCommonMetaData('Approvalfront');
            wrpObj.back = Url+ embobj.ProductYETIKey__c +'/'+ CommonUtil.getCommonMetaData('ApprovalBack');
            wrapList.add(wrpObj);
            system.debug(wrapList);
        }
      return wrapList;
     }catch(exception e){
         return null;
       }
     }

}