FusionDev Backup1/src/objects/EmbellishedArt__c.object
<CustomObject>
    <description>This Object holds the design records with a set of values which are to be defined before the design has to be released to SAP as a material.</description>
    <fields>
        <fullName>ArtName__c</fullName>
        <description>The name of the design. This is an internal name; not displayed to customers.</description>
        <inlineHelpText>Format : [Alphanumeric] [Alphanumeric].. [Alphanumeric].</inlineHelpText>
        <label>Art Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ArtYETIKey__c</fullName>
        <description>This is a key which uniquely defines this design in all systems.</description>
        <inlineHelpText>One must strictly enter only alphanumeric characters or a hyphen. 
Note : No multiple hyphens &apos; --&apos; or a space between words. 
Format : [Text/Numeric]-[Text/Numeric]</inlineHelpText>
        <label>YETI Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <description>This is an administratively controlled list of categories for art custom art design.</description>
        <label>Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Collegiate</fullName>
                </value>
                <value>
                    <fullName>Greek</fullName>
                </value>
                <value>
                    <fullName>Nascar</fullName>
                </value>
                <value>
                    <fullName>National Parks</fullName>
                </value>
                <value>
                    <fullName>Coastal</fullName>
                </value>
                <value>
                    <fullName>Fish</fullName>
                </value>
                <value>
                    <fullName>Hunt</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Outdoor</fullName>
                </value>
                <value>
                    <fullName>State</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsPremium__c</fullName>
        <description>This specifies if the design is a standard or premium one.</description>
        <label>Is Premium</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Embellished Art</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Embellished Art</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Embellished Arts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FusionDev Backup1/src/objects/EmbellishedProduct__c.object
<CustomObject>
    <description>A design is always coupled, or applied to, a customized product.  So a design is often not useful on it&apos;s own; you need to know what customized product it&apos;s being applied to to understand specifically how the art of a given design should be.</description>
    <fields>
        <fullName>ProductName__c</fullName>
        <description>The name of the embellished product. This is an internal name; not displayed to customers.</description>
        <inlineHelpText>Format : [Alphanumeric] [Alphanumeric].. [Alphanumeric].</inlineHelpText>
        <label>Product Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ProductYETIKey__c</fullName>
        <description>Generically put, this is a key which uniquely defines this design in all systems.  Specifically, this is needed by SFCC to identify the cup against the Art Gallery.  Also, this value is also used in APIs for images, as well as constructing well-known paths against Amazon S3.    More discussion can be found here: Universal Product Key (UPK)</description>
        <inlineHelpText>One must strictly enter only alphanumeric characters or a hyphen. 
Note : No multiple hyphens &apos; --&apos; or a space between words. 
Format : [Text/Numeric]-[Text/Numeric]</inlineHelpText>
        <label>YETI Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Embellished Product</label>
    <nameField>
        <displayFormat>EP-{0000}</displayFormat>
        <label>Embellished Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Embellished Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FusionDev Backup1/src/classes/ArtDesignController_Test.cls
/*
######################################################################################################################
Name:       ArtDesignController_Test.apxc 
Description:  Test class for ArtDesignController 
S.NO:     Date      Version      Author             Summary of Changes 
**********************************************************************************************************************
  1     4/20/2018    1.0       Ranjith Thadakala      Initial Release
**********************************************************************************************************************
*/

@isTest
private class ArtDesignController_Test {
    
    private static EmbellishedProduct__c embProduct;
    private static EmbellishedArt__c embArt;
    
 /* creating test data */    
    @isTest
    private static void setupTestData(){
       
       embProduct = new EmbellishedProduct__c();
       embProduct.ProductName__c = 'RamblerBottle';
       embProduct.ProductYETIKey__c = 'rambler-bottle';
       insert embProduct;
       
       embArt = new EmbellishedArt__c();  
       embArt.ArtName__c = 'Appalachian State';
       embArt.Category__c='Collegiate';
       embArt.IsPremium__c='Yes';
       embArt.ArtYETIKey__c='appalachian-state';
       insert embArt;
}
  /* case 1 positive */
   @isTest
    private static void getProducts_Test(){
        List<ArtDesignController.ArtDesignWrapper> ArtDesignWrapper;
        setupTestData();
        try{
        Test.startTest();
        ArtDesignWrapper = ArtDesignController.getProducts(embArt.Id);
        Test.stopTest();
        
        system.assertEquals(ArtDesignWrapper[0].productName, 'RamblerBottle');
        system.assertEquals(ArtDesignWrapper[0].laser, 'https://s3.amazonaws.com/howard-sandbox/test/designs/premium/collegiate/appalachian-state/rambler-bottle/laser-ready.bmp');
     }
        catch(exception e){
            
           system.assertEquals(ArtDesignWrapper, null); 
            
        }
    
    }
    /* case 2 negative */
    @isTest
     private static void getProducts_Test1(){
        List<ArtDesignController.ArtDesignWrapper> ArtDesignWrapper;
         EmbellishedProduct__c embprd = new EmbellishedProduct__c();
        try{
            
        Test.startTest();
        ArtDesignWrapper = ArtDesignController.getProducts(embprd.Id);
        Test.stopTest();
        
        system.assertEquals(ArtDesignWrapper[0].productName, 'RamblerBottle');
        system.assertEquals(ArtDesignWrapper[0].laser, 'https://s3.amazonaws.com/howard-sandbox/test/designs/premium/collegiate/appalachian-state/rambler-bottle/laser-ready.bmp');
     }
        catch(exception e){
            system.assertEquals(e.getMessage(), e.getMessage());
           system.assertEquals(ArtDesignWrapper, null); 
            
        }
    
    }
    
    
    
}