FusionDev Backup1/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Company_Email__c</fullName>
        <label>Company Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Lead_Assignment_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Assignment Rule</label>
        <referenceTo>Lead_Assignment_Rule__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

FusionDev Backup1/src/objects/Lead_Assignment_Rule__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Lead_Assignment_Rules_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <externalId>true</externalId>
        <label>Zip Code</label>
        <length>5</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Lead Assignment Rule</label>
    <nameField>
        <label>Lead Assignment Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Assignment Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FusionDev Backup1/src/classes/TestDataUtility.cls
@isTest
public class TestDataUtility {
    
    public static User newUser(String newUserName) {
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User'];
        User u = new User(UserName = newUserName, EMail = newUserName, Alias = newUserName.left(8), CommunityNickname = newUserName, LastName = newUserName, ProfileId = p.Id, TimeZoneSidKey = 'America/Los_Angeles', LocaleSidKey = 'en_US', EmailEncodingKey = 'ISO-8859-1', LanguageLocaleKey = 'en_US' );
        insert u;
        u = [SELECT Id FROM User WHERE UserName =: newUserName];
        return u;
    }
    
    public static Lead newLead(String leadLastName, String leadCompany, Boolean approved) {
        Lead l = new Lead(LastName = leadLastName, Company = leadCompany, Company_Email__c = 'name@company.com', Email = 'company@company.com', Street = 'Test Street', City = 'Test City', State = 'NV', PostalCode = '89521', Country = 'USA', Phone = '7757777777', Approved__c = approved);
        insert l;
        l = [SELECT Id, OwnerId FROM Lead WHERE LastName=:leadLastName ORDER BY Id DESC LIMIT 1];
        return l; 
    }

    public static Lead_Assignment_Rule__c newLeadAssignmentRule(Id salesRep, String zipCode) {
        Lead_Assignment_Rule__c lar = new Lead_Assignment_Rule__c(Name = zipcode, Zip_Code__c = zipcode, Sales_Rep__c = salesRep);
        insert lar;
        lar = [SELECT Id, Zip_Code__c, Sales_Rep__c FROM Lead_Assignment_Rule__c WHERE Zip_Code__c =: zipCode];         
        return lar;
    }
    
       
}