FusionDev Backup1/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Lead_Assigned_by_State__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lead Assigned by State</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead_Assigned_by_Zip_Code__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lead Assigned by Zip Code</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead_Assignment_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Assignment Rule</label>
        <referenceTo>Lead_Assignment_Rule__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <businessProcess>Dealer</businessProcess>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

FusionDev Backup1/src/objects/Lead_Assignment_Rule__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Lead_Assignment_Rules_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <externalId>true</externalId>
        <label>State</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <externalId>true</externalId>
        <label>Zip Code</label>
        <length>5</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Lead Assignment Rule</label>
    <nameField>
        <label>Lead Assignment Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Assignment Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FusionDev Backup1/src/classes/LeadUtil.cls
public class LeadUtil{

    //The leadAssignment method assigns leads owners based on zip code (lookups user based on zip code in lead_assignment__c object)
    public static void leadAssignment(List<Lead> leads) {

        //Create list of zip codes on new leads
        List<String> zipCodes = new List<String>();
        for (Lead l : leads) {
            if (l.PostalCode <> '' && l.PostalCode <> null) {
                zipCodes.add(l.PostalCode.Left(5));
            }
        }

        //Create list of states on new leads
        List<String> states = new List<String>();
        for (Lead l : leads) {
            if (l.State <> '' && l.State <> null) {
                states.add(l.State);
            }
        }

        //Create map of zip codes to Sales Reps for assignment
        List<Lead_Assignment_Rule__c> leadAssignRulesZip = [SELECT Zip_Code__c, Sales_Rep__c FROM Lead_Assignment_Rule__c WHERE Zip_Code__c IN : zipCodes];
        Map<String,Lead_Assignment_Rule__c> zipToAssignRuleZipMap = new Map<String,Lead_Assignment_Rule__c>();
        for (Lead_Assignment_Rule__c lar : leadAssignRulesZip) {
            zipToAssignRuleZipMap.put(lar.Zip_Code__c, lar);
        }

        //Create map of States to Sales Reps for assignment
        List<Lead_Assignment_Rule__c> leadAssignRulesState = [SELECT State__c, Sales_Rep__c FROM Lead_Assignment_Rule__c WHERE State__c IN : states];
        Map<String,Lead_Assignment_Rule__c> zipToAssignRuleStateMap = new Map<String,Lead_Assignment_Rule__c>();
        for (Lead_Assignment_Rule__c lar : leadAssignRulesState) {
            zipToAssignRuleStateMap.put(lar.State__c, lar);
        }


    String recordTypeName = 'Dealer'; // 
      Map<String,Schema.RecordTypeInfo> rtMapByName = Schema.SObjectType.Lead.getRecordTypeInfosByName();
      Schema.RecordTypeInfo rtInfo =  rtMapByName.get(recordTypeName);
      id recordTypeId = rtInfo.getRecordTypeId();
    
        //Assign new leads to appropriate owner (based on zip) and set Lead Assigned by Zip Code flag
        // List<RecordType> rt [SELECT Id FROM RecordType FROM Lead WHERE Name = Dealer LIMIT 1];
        for (Lead l : leads) {
         if(l.RecordTypeId == recordTypeId) {
          Integer counter = 0;
    
            if (zipToAssignRuleZipMap.containsKey(l.PostalCode)) {
                l.Lead_Assigned_by_Zip_Code__c = true;
                l.OwnerId = zipToAssignRuleZipMap.get(l.PostalCode).Sales_Rep__c;
                
            }
        }

     //   for (lead l : leads) {
            if (zipToAssignRuleStateMap.containsKey(l.State) && l.Lead_Assigned_by_Zip_Code__c == false) {
                l.Lead_Assigned_by_State__c = true;
                l.OwnerId = zipToAssignRuleStateMap.get(l.State).Sales_Rep__c;
            }
        }

    }
}