FusionDev Backup1/src/objects/Order__c.object
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

FusionDev Backup1/src/objects/Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>Order_Line__c</fullName>
        <label>Order Line</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Order Line</label>
    <nameField>
        <label>Order Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FusionDev Backup1/src/classes/Yeti_printOrderControllerTest.cls
/*
Author        :  Rakshit Virmani (Appirio)
Created Date  :  23rd March 2017
Name          :  Yeti_printOrderControllerTest
Description   :  Test Class for Yeti_printOrderController 
*/
@isTest
public class Yeti_printOrderControllerTest {
  @testSetup
  static void createTestData(){
    YETI_TestDataFactory ytdf = new YETI_TestDataFactory();
    Account acc = ytdf.createAccount('Test Account', true);
    Order__c ord = ytdf.createOrder('Test Order', acc.Id, true);
    List<Order_Line__c> lstInvoiceLines = ytdf.createMultipleOrderLines('TestOrderLines',ord.Id,5,true);
  }
  
  static testmethod void testPrintOrderPage(){
    Test.startTest();
      Order__c inv = [SELECT Id,Name FROM Order__c WHERE Name =: 'Test Order' LIMIT 1];
      ApexPages.currentPage().getParameters().put('id',inv.Id);
      Yeti_PrintOrderController ypdc = new Yeti_PrintOrderController();
      system.assertEquals(true, ApexPages.currentPage().getParameters().get('id') != null);
    Test.stopTest();
  }
}